Si usas callbacks debes de arrojar una excepción  tu mismo con throw y tomarla con try-catch tambien

Con callbacks se suele acordar que se les pasará dos parámetros (algo que no he hecho.... lo siento). El primero "err", cuando "err" no es undefined es que hubo un error